# netlify.toml

[build]
  # Direktori output frontend setelah 'npm run build' selesai
  publish = "dist"
  # Perintah untuk membangun frontend Anda
  command = "npm run build"

[dev]
  command = "npm run start"
  targetPort = 8080
  publish = "dist"